"""Write DESIGN_SUMMARY.md: a plain-text digest of the KiCad project.

graphify (and any chat) can't read .kicad_* files, so this flattens the
schematic sheets and the board into markdown. Re-run after editing the design:
    python hardware/kicad/kicad_summary.py [kicad_project_dir]
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent
TOK = re.compile(r'\(|\)|"(?:\\.|[^"\\])*"|[^\s()]+')


def parse(text):
    stack = [[]]
    for t in TOK.findall(text):
        if t == '(':
            stack.append([])
        elif t == ')':
            node = stack.pop()
            stack[-1].append(node)
        else:
            stack[-1].append(t[1:-1] if t.startswith('"') else t)
    return stack[0][0]


def kids(node, name):
    return [c for c in node if isinstance(c, list) and c and c[0] == name]


def props(node):
    return {p[1]: p[2] for p in kids(node, 'property')}


def sheet_summary(path):
    root = parse(path.read_text(encoding='utf-8'))
    parts = []
    for s in kids(root, 'symbol'):
        p = props(s)
        ref = p.get('Reference', '?')
        if ref.startswith('#'):  # power flags / symbols
            continue
        parts.append((ref, p.get('Value', ''), p.get('Footprint', ''), p.get('LCSC', '')))
    labels = sorted({l[1] for k in ('global_label', 'hierarchical_label', 'label') for l in kids(root, k)})
    power = sorted({props(s).get('Value', '') for s in kids(root, 'symbol')
                    if props(s).get('Reference', '').startswith('#PWR')})
    sheets = [(props(s).get('Sheetname'), props(s).get('Sheetfile')) for s in kids(root, 'sheet')]
    return parts, labels, power, sheets


def natkey(ref):
    m = re.match(r'([A-Za-z]+)(\d*)', ref)
    return (m.group(1), int(m.group(2) or 0)) if m else (ref, 0)


def board_summary(path):
    text = path.read_text(encoding='utf-8')
    root = parse(text)
    fps = []
    for f in kids(root, 'footprint'):
        layer = kids(f, 'layer')[0][1]
        at = kids(f, 'at')[0][1:]
        ref = props(f).get('Reference', '?')
        fps.append((ref, f[1], layer, ' '.join(at)))
    nets = sorted(set(re.findall(r'\(net (?:\d+ )?"([^"]+)"\)', text)))
    edges = [g for k in ('gr_line', 'gr_rect', 'gr_arc', 'gr_poly')
             for g in kids(root, k) if kids(g, 'layer') and kids(g, 'layer')[0][1] == 'Edge.Cuts']
    xs, ys = [], []
    for g in edges:
        for k in ('start', 'end', 'mid'):
            for pt in kids(g, k):
                xs.append(float(pt[1])); ys.append(float(pt[2]))
    size = f'{max(xs) - min(xs):.1f} x {max(ys) - min(ys):.1f} mm' if xs else 'unknown'
    gen = kids(root, 'general')
    thick = kids(gen[0], 'thickness')[0][1] if gen and kids(gen[0], 'thickness') else '?'
    tracks = len(kids(root, 'segment')) + len(kids(root, 'arc'))
    vias = len(kids(root, 'via'))
    zones = sorted({n[-1] for z in kids(root, 'zone') for n in kids(z, 'net') + kids(z, 'net_name') if n[-1]})
    return fps, nets, size, thick, tracks, vias, zones


def main():
    out = ['# AI Calculator PCB - KiCad design summary', '',
           f'Generated by `hardware/kicad/kicad_summary.py` from the KiCad 10 project in `{HERE.resolve()}`. '
           'Do not edit by hand. Context and decisions: `Claude outputs/AI_CALC_PCB_HANDOFF.md`.', '']
    _, _, _, sheets = sheet_summary(HERE / 'ai_calc.kicad_sch')
    out += ['## Hierarchy', '', 'Root sheet `ai_calc.kicad_sch` contains:', '']
    out += [f'- **{name}** (`{file}`)' for name, file in sheets] + ['']
    for name, file in sheets:
        parts, labels, power, _ = sheet_summary(HERE / file)
        out += [f'## Sheet: {name} (`{file}`)', '']
        if power:
            out += ['Power rails: ' + ', '.join(power), '']
        if labels:
            out += ['Net labels: ' + ', '.join(labels), '']
        out += ['| Ref | Value | Footprint | LCSC |', '|---|---|---|---|']
        out += [f'| {r} | {v} | {f} | {l} |' for r, v, f, l in sorted(parts, key=lambda p: natkey(p[0]))] + ['']
    fps, nets, size, thick, tracks, vias, zones = board_summary(HERE / 'ai_calc.kicad_pcb')
    out += ['## Board (`ai_calc.kicad_pcb`)', '',
            f'- Outline extent: {size}, thickness {thick} mm, 2 layers (F.Cu = component side facing back cover, B.Cu = key pads + e-paper)',
            f'- {len(fps)} footprints, {tracks} track segments, {vias} vias',
            f'- Copper zones on: {", ".join(zones) or "none"}',
            f'- Nets ({len(nets)}): ' + ', '.join(nets), '',
            '| Ref | Footprint | Layer | Position (x y rot) |', '|---|---|---|---|']
    out += [f'| {r} | {f} | {l} | {a} |' for r, f, l, a in sorted(fps, key=lambda p: natkey(p[0]))] + ['']
    libs = sorted(p.stem for p in (HERE / 'ai_calc.pretty').glob('*.kicad_mod'))
    out += ['## Custom footprint library `ai_calc.pretty`', ''] + [f'- {n}' for n in libs] + ['']
    (HERE / 'DESIGN_SUMMARY.md').write_text('\n'.join(out), encoding='utf-8')
    print(f'wrote DESIGN_SUMMARY.md: {len(sheets)} sheets, {len(fps)} footprints, {len(nets)} nets')


if __name__ == '__main__':
    main()
