"""Generate core/font_data.cpp from the public-domain X11 misc-fixed 5x7 font.

Usage: python3 tools/gen_font.py /usr/share/fonts/X11/misc/5x7.pcf.gz > core/font_data.cpp
"""
import gzip, sys, io
from PIL import PcfFontFile as P

WANTED = (
    [chr(c) for c in range(32, 127)]
    + list("°±²³µ·×÷¹¼½¾¬")
    + list("→←↑↓↔⇌≈≠≤≥√∞∫∑∆∂∇∝∠⊥∥−′″…✓✗⋅")
    + list("ΑΒΓΔΘΛΞΠΣΦΨΩαβγδεζηθικλμνξπρστυφχψω")
    + list("⁰ⁱ⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁿ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎")
    + list("ÅℏΩ")
)

class Full(P.PcfFontFile):
    def __init__(self, fp):
        self.charset_encoding = "iso8859-1"
        magic = P.l32(fp.read(4))
        count = P.l32(fp.read(4))
        self.toc = {}
        for _ in range(count):
            t = P.l32(fp.read(4))
            self.toc[t] = P.l32(fp.read(4)), P.l32(fp.read(4)), P.l32(fp.read(4))
        self.fp = fp
        self.info = self._load_properties()
        self.metrics = self._load_metrics()
        self.bitmaps = self._load_bitmaps(self.metrics)
        fp, fmt, i16, i32 = self._getformat(P.PCF_BDF_ENCODINGS)
        self.fc, self.lc = i16(fp.read(2)), i16(fp.read(2))
        self.fr, self.lr = i16(fp.read(2)), i16(fp.read(2))
        i16(fp.read(2))
        n = (self.lc - self.fc + 1) * (self.lr - self.fr + 1)
        self.offs = [i16(fp.read(2)) for _ in range(n)]

    def index(self, cp):
        row, col = cp >> 8, cp & 0xFF
        if not (self.fr <= row <= self.lr and self.fc <= col <= self.lc):
            return None
        o = self.offs[(row - self.fr) * (self.lc - self.fc + 1) + (col - self.fc)]
        return None if o == 0xFFFF else o

data = gzip.open(sys.argv[1]).read()
f = Full(io.BytesIO(data))
ASC = 6  # baseline row inside the 7-row cell
out, missing = [], []
seen = set()
for ch in WANTED:
    cp = ord(ch)
    if cp in seen:
        continue
    seen.add(cp)
    ix = f.index(cp)
    if ix is None:
        missing.append(ch)
        continue
    xsize, ysize, left, right, width, ascent, descent, attr = f.metrics[ix]
    bm = f.bitmaps[ix]
    rows = [0] * 7
    for y in range(ysize):
        for x in range(xsize):
            if bm.getpixel((x, y)):
                cx, cy = left + x, ASC - ascent + y
                if 0 <= cx < 5 and 0 <= cy < 7:
                    rows[cy] |= 1 << (4 - cx)
    out.append((cp, rows, ch))

print("// Generated by tools/gen_font.py from the X11 misc-fixed 5x7 font (public domain).")
print("// Each glyph: 7 rows, low 5 bits per row, bit 4 = leftmost pixel.")
print('#include "font.h"')
print("namespace calc {")
print("const Glyph kGlyphs[] = {")
for cp, rows, ch in out:
    safe = ch if ch not in "\\" else "backslash"
    print("  {0x%04X, {%s}}, // %s" % (cp, ",".join("0x%02X" % r for r in rows), safe))
print("};")
print("const int kGlyphCount = %d;" % len(out))
print("}  // namespace calc")
if missing:
    sys.stderr.write("missing: " + "".join(missing) + "\n")
