"""v15-LCD: 1:1 paper jig for placing the LCD on the board's KEY side (the KEEPOUTS marker is only in the KiCad file,
it is not printed on the board).

    python lcd_position_jig_v15.py    -> lcd_position_jig_v15.svg

Drawn as seen from the KEY side (KiCad x mirrored), display end up. The top part of the board outline, the 1.0 x 20 mm
tail slot and the LCD backlight outline (49.72 x 25.8, centred on KiCad (151.30, 93.10), = KEEPOUTS rectangle) are taken
from hardware/kicad_v15_lcd/ai_calc_v15_lcd.kicad_pcb (read only). Use: print at 100 %, check the 50 mm bar, cut along the
board's top edge and side edges and cut OUT the panel window and the slot; lay the paper on the key side with its edges on the
board's edges, drop the panel into the window, tail towards the slot.
"""
import importlib.util, os

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("b15", os.path.join(HERE, "build_final_assembly_v15.py"))
B = importlib.util.module_from_spec(spec)
spec.loader.exec_module(B)
info = B.R.board_info()

Y_CUT = 125.0                              # draw the board down to this KiCad y (the LCD end only)
BL = (B.LCD_BL_X[0], B.LCD_BL_X[1], 93.1 - B.LCD_BL_H / 2, 93.1 + B.LCD_BL_H / 2)
AA = (150.0 - 42.72 / 2, 150.0 + 42.72 / 2, 93.1 - 22.70 / 2, 93.1 + 22.70 / 2)
SLOT = (B.LCD_SLOT_XK - 0.5, B.LCD_SLOT_XK + 0.5, 83.1, 103.1)
PW, PH = 210.0, 297.0
OX, OY = 105.0 + 150.0, 40.0 - 62.0         # page x = OX - x_kicad (mirrored: key side), page y = y_kicad + OY

def P(x, y):
    return OX - x, y + OY

def rect(r, **kw):
    x0, y0 = P(r[1], r[2]); a = " ".join('%s="%s"' % (k.replace("_", "-"), v) for k, v in kw.items())
    return '<rect x="%.3f" y="%.3f" width="%.3f" height="%.3f" %s/>' % (x0, y0, r[1] - r[0], r[3] - r[2], a)

out = ['<svg xmlns="http://www.w3.org/2000/svg" width="210mm" height="297mm" viewBox="0 0 210 297">',
       '<rect width="210" height="297" fill="white"/>']
for (a, b) in info["segs"]:
    if a[1] > Y_CUT and b[1] > Y_CUT:
        continue
    if 180 < a[0] < 182 and 82 < a[1] < 104:     # the slot is drawn separately as a cut-out
        continue
    (x0, y0), (x1, y1) = P(*a), P(*b)
    out.append('<line x1="%.3f" y1="%.3f" x2="%.3f" y2="%.3f" stroke="black" stroke-width="0.3"/>' % (x0, y0, x1, y1))
x0, y0 = P(info["bbox"][1], Y_CUT); x1, _ = P(info["bbox"][0], Y_CUT)
out.append('<line x1="%.3f" y1="%.3f" x2="%.3f" y2="%.3f" stroke="black" stroke-width="0.3" stroke-dasharray="2 1.5"/>' % (x0, y0, x1, y0))
out.append(rect(BL, fill="#d9d9d9", stroke="black", stroke_width="0.35"))
out.append(rect(AA, fill="none", stroke="#555", stroke_width="0.2", stroke_dasharray="1 1"))
out.append(rect(SLOT, fill="#d9d9d9", stroke="black", stroke_width="0.3"))
cx, cy = P(151.3, 93.1)
T = lambda x, y, s, t, a="middle", w="normal": out.append(
    '<text x="%.2f" y="%.2f" font-family="Arial" font-size="%.2f" text-anchor="%s" font-weight="%s">%s</text>' % (x, y, s, a, w, t))
T(cx, cy - 2, 3.2, "CUT OUT: LCD backlight 49.72 x 25.80", w="bold")
T(cx, cy + 3, 2.4, "dashed = picture (active area) 42.72 x 22.70")
T(cx, cy + 7, 2.4, "tail end of the panel -> towards the slot")
sx, sy = P(181.0, 103.1)
T(sx, sy + 4, 2.4, "CUT OUT: slot 1 x 20")
T(105, 12, 4.0, "AI calculator v15-LCD: LCD position jig (1:1)", w="bold")
T(105, 18, 2.8, "Seen from the KEY side, display end up. Print at 100 % (Actual size). Check the 50 mm bar first.")
T(105, 22.5, 2.8, "Cut along the board edge lines, cut out the grey panel window and the slot. Lay it on the key side,")
T(105, 27, 2.8, "edges on the board's edges and its slot over the board's slot, then drop the panel into the window.")
gap = B.LCD_SLOT_XK - 0.5 - B.LCD_BL_X[1]
T(105, 175, 2.8, "Checks without the jig: panel centred along the slot's 20 mm length (slot centre = panel centre),")
T(105, 179.5, 2.8, "and its tail-end edge %.1f mm from the slot's near edge. Then the dry fit through the window decides." % gap)
out.append('<line x1="20" y1="195" x2="70" y2="195" stroke="black" stroke-width="0.8"/>')
T(45, 200, 2.8, "50 mm: measure this bar")
T(105, 290, 2.2, "Generated by lcd_position_jig_v15.py from hardware/kicad_v15_lcd/ai_calc_v15_lcd.kicad_pcb (review 13 board, 2026-10-08).")
out.append("</svg>")
open(os.path.join(HERE, "lcd_position_jig_v15.svg"), "w", encoding="utf8").write("\n".join(out))
print("lcd_position_jig_v15.svg written; backlight edge to slot edge %.2f mm" % gap)
